package co.morillas.auth.core.exception

class UsernameExistsException(): RuntimeException("Username already in use")